[package]
name = "wayshot"
version = "0.1.0"
edition = "2021"
authors = ["Shinyzenith <aakash@shinyzenith.xyz>"]

[dependencies]
smithay-client-toolkit = "0.15.3"
image = "0.24.0"
tempfile = "3.3.0"

[[bin]]
name = "wayshot"
path = "src/main.rs"
